version: "3.9"

services:

  api:
    build: ./server
    container_name: content-platform-api
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7
    container_name: content-platform-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: content-platform-redis
    ports:
      - "6379:6379"

volumes:
  mongo-data: